# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# This is the code written by the instructor Ryan Hageman. Student's code shouldn't have this line in it unless they've downloaded my code from GitHub instead of writing their own code.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e247772db639b4bac3f4451f2b30925fd819796b38f336c46a7d44532d5e2472306d6b0f7816fb2778b0a1e31c53016dd5468a693e3258fab350395a6d136827

test:
  secret_key_base: b639920b152afb31befa6f2e560c8d2e36958d30febd26e06b8ba217cebac446004afb8078da38ed31d5a97ab4e593bf45a5fff99463847dbb97d76b3678c852

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
